name: .NET

on:
  push:
    branches:
    - main
    - develop
    - feature/**
  pull_request:
    branches:
    - main
    - develop
    - feature/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd src/CurrentTimestamps/
        dotnet restore CurrentTimestamps.sln
    - name: Build
      run: |
        cd src/CurrentTimestamps/
        dotnet build CurrentTimestamps.sln --no-restore
    - name: Test
      run: |
        cd src/CurrentTimestamps/
        dotnet test CurrentTimestamps.sln --no-build --verbosity normal
